/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects. It is committed here so
// a fresh checkout has complete TypeScript context before the first dev run.
